### PR TITLE
Upgrade beta7

### PR DESCRIPTION
**Pull request by kenghooi-teoh**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Tested on 
- [X ] Windows  
- [ ] Linux Ubuntu  
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

Assign a reviewer to review your code.

### CODE REVIEW

**Comment by KianYang-Lee** [comment]
Error for BirdClassification file

<code>C:\TrainingLabs\dl4j-labs\src\main\java\ai\certifai\solution\classification\BirdClassification.java:11:39
java: package org.deeplearning4j.core.storage does not exist</code>

**Comment by codenamewei** [comment]
readme update to version 7 too, thanks @ameliepeter 
Screenshot 2020-12-01 222419

**Review by ameliepeter — COMMENTED** [review]
review completed. 
@kenghooi-teoh

**Comment by kenghooi-teoh** [comment]
@KianYang-Lee I can't reproduce this. Is your local branch up to date? 

> Error for BirdClassification file
> 
> `C:\TrainingLabs\dl4j-labs\src\main\java\ai\certifai\solution\classification\BirdClassification.java:11:39 java: package org.deeplearning4j.core.storage does not exist`
> 
> @kenghooi-teoh

**Comment by KianYang-Lee** [comment]
> @KianYang-Lee I can't reproduce this. Is your local branch up to date?
> 
> > Error for BirdClassification file
> > `C:\TrainingLabs\dl4j-labs\src\main\java\ai\certifai\solution\classification\BirdClassification.java:11:39 java: package org.deeplearning4j.core.storage does not exist`
> > @kenghooi-teoh

@kenghooi-teoh The branch was since updated since i posted the issue, so the issue is fixed.

**Review by KianYang-Lee — COMMENTED** [review]
Reviewed what was necessary. Relevant files look good. Anyone else has not reviewed their part @evanyeohboonkhai  @guanyu-certifai  If not suggest that we can merge this PR and call it a day @kenghooi-teoh

**Comment by kenghooi-teoh** [comment]
@KianYang-Lee @ameliepeter 
Got the following error when running classification/transferlearning/EditBottleneckAndExtendModel.java, can you reproduce the same error?

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
	at org.deeplearning4j.util.ModelSerializer.loadZipData(ModelSerializer.java:990)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:470)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:463)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:648)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:604)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:101)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:54)
	at ai.certifai.solution.classification.transferlearning.EditAtBottleneckAndExtendModel.main(EditAtBottleneckAndExtendModel.java:84)

**Comment by kenghooi-teoh** [comment]
> @KianYang-Lee @ameliepeter
> Got the following error when running classification/transferlearning/EditBottleneckAndExtendModel.java, can you reproduce the same error?
> 
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
> Caused by: java.lang.OutOfMemoryError: Java heap space
> at java.util.Arrays.copyOf(Arrays.java:3236)
> at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
> at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
> at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
> at org.deeplearning4j.util.ModelSerializer.loadZipData(ModelSerializer.java:990)
> at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:470)
> at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:463)
> at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:648)
> at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:604)
> at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:101)
> at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:54)
> at ai.certifai.solution.classification.transferlearning.EditAtBottleneckAndExtendModel.main(EditAtBottleneckAndExtendModel.java:84)

error gone once i increased heap space, didn't realise the heap space i use is different between branches

**Pull request merged**
